version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/requirements"
    schedule:
      interval: weekly
      day: monday
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/app4-dashboard/frontend"
    schedule:
      interval: weekly
      day: monday
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/app1-colmap"
    schedule:
      interval: weekly
      day: monday
    ignore:
      - dependency-name: "nvidia/cuda"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: docker
    directory: "/app1-colmap/dronegs"
    schedule:
      interval: weekly
      day: monday
    ignore:
      - dependency-name: "nvidia/cuda"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "python"
        versions:
          - ">= 3.13"

  - package-ecosystem: docker
    directory: "/app2-ia"
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: docker
    directory: "/app3-processing"
    schedule:
      interval: weekly
      day: monday
    ignore:
      - dependency-name: "python"
        versions:
          - ">= 3.13"

  - package-ecosystem: docker
    directory: "/app4-dashboard/api"
    schedule:
      interval: weekly
      day: monday
    ignore:
      - dependency-name: "python"
        versions:
          - ">= 3.13"

  - package-ecosystem: docker
    directory: "/app4-dashboard/frontend"
    schedule:
      interval: weekly
      day: monday
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
