{{- if not .Values.storage.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: drone-ai-storage
  namespace: {{ include "drone-ai.namespace" . }}
  labels:
    {{- include "drone-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  s3-access-key: {{ .Values.storage.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.storage.s3SecretKey | quote }}
  database-url: {{ .Values.storage.databaseUrl | quote }}
{{- end }}
